### ISSUE TITLE
Please stop with un-needed comments

### ISSUE THREAD

**Issue by ghost** [Oliwerix/1bitvm.c#3]
comments like these are not needed and not wanted!
please stop!
              Looks good to me

_Originally posted by @adimineman in https://github.com/Oliwerix/1bitvm.c/pull/2#pullrequestreview-1294777969_

**Comment by ghost** [comment]
as stated in https://github.com/Oliwerix/1bitvm.c/issues/5 , i encourage @Oliwerix to reopen this issue

**Comment by sijanec** [comment]
> as stated in #5 , i encourage @Oliwerix to reopen this issue

alo nehi spamat, github avtomatsko backreferenca išjuje

**Comment by ghost** [comment]
Fr? če Omenim #5 alpa #4 je problem?
